# Generated by Django 4.2.7 on 2023-11-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order_no',
        ),
    ]
