# Generated by Django 4.2.7 on 2023-11-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_remove_category_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('half_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.category')),
            ],
        ),
    ]
