# Generated by Django 4.2.7 on 2023-11-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='half_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
