# Generated by Django 4.2.7 on 2023-11-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_menu_menucategory_menufood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.category'),
        ),
    ]
